version: '3.8'

services:
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ~{.Env.MONGO_INITDB_ROOT_USERNAME }
      MONGO_INITDB_ROOT_PASSWORD: ~{.Env.MONGO_INITDB_ROOT_PASSWORD }
      MONGO_INITDB_DATABASE: ~{ .Env.MONGO_INITDB_DATABASE }
    ports:
      - "27017:27017"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      URI: mongodb://{{ .Env.MONGO_INITDB_ROOT_USERNAME }}:{{ .Env.MONGO_INITDB_ROOT_PASSWORD }}@mongo:27017/{{ .Env.MONGO_INITDB_DATABASE }}?authSource=admin
